---
output: pdf_document
---


In Class Exercise
========================================================

The birth weight of a baby is of interest to health officials since many studies have shown possible links between weight and conditions later in life, such as obesity or diabetes.  The data set `Girls2004` consists of a random sample of 40 baby girls born in Alaska and 40 baby girls born in Wyoming.  These babies also had a gestation period of at least 37 weeks and were single births. 


Import the data `Girls2004.csv` available from [http:\\www1.appstate.edu/arnholta/Data/](http:\\www1.appstate.edu/arnholta/Data/).



  * Perform some exploratory data analysis and obtain summary statistics on the weights of baby girls born in Wyoming and Alaska (do separate analyses for each state).
  
  * Bootstrap the difference in means, plot the distribution, and give summary statistics.  Obtain a 95% bootstrap percentile confidence interval and interpret this interval.
  
  * What is the bootstrap estimate of the bias?  What fraction of the bootstrap standard error does it represent?
  
  * Conduct a permutation test to calculate the difference in mean weights and state your conclusion.
  
  * For what population(s) if any, does this conclusion hold?  Explain.
