

Most of the material in the notes is taken from the class text _Mathematical Statistics with Resampling and `R`_ by Laura Chihara and Tim Hesterberg with slight modifications.  Some material in the notes is also taken from the first chapter of _Practicing Statistics: Guided Investigations for the Second Course_ by Shonda Kuiper and Jeffrey Sklar.  There are a number of places to get help with `R`.  The class text has some material online at: [https://sites.google.com/site/chiharahesterberg/rtutorials](https://sites.google.com/site/chiharahesterberg/rtutorials).  

* The data sets for _Mathematical Statistics with Resampling and `R`_ stored as `*.csv` files are available from [https://github.com/alanarnholt/STT3850/tree/gh-pages/DataCSV](https://github.com/alanarnholt/STT3850/tree/gh-pages/DataCSV) --- Note:  once a file is selected, click the `raw` button in github to strip off the html.

* The data sets for _Mathematical Statistics with Resampling and `R`_ are also available in the `R` package `resampledata`.

```{r}
library(resampledata)
head(Verizon)
```

