---
title: "Tentative STT 3850 Course Schedule - Spring 2027"
output:
  html_document:
    css: ../css/style.css
    highlight: textmate
    theme: yeti
  pdf_document: default
---

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>

________________________________

### General Notes: {-}

```{block, note-text, type='rmdnote'}
1.  Please bring a notebook and pencil to every class.
2.  The principal documents for this course are [_ModernDive: An Introduction to Statistical and Data Sciences via R_](https://moderndive.com) (MD), [_Data Science with R_](https://stat-ata-asu.github.io/R_DS_BD2020/) (DSWR), and _Mathematical Statistics with Resampling and R_ (MSWR) -available inside the [ASULEARN](https://asulearn.appstate.edu/user/index.php?id=180523) course page.
3.  Problem Set (PS) assignments are generally due on Thursdays by 5:00 pm
4.  The links for the problem sets and the sampling distribution assignment in this document may only work for the instructor!  To accept each of these assignments, go to [ASULEARN](https://asulearn.appstate.edu/course/view.php?id=159655) and click on the appropriate link in the [GitHub Classroom Invitation Links for Assignments](https://asulearn.appstate.edu/course/view.php?id=167073) block. 
5. [QUARTO cheat sheet](https://images.datacamp.com/image/upload/v1676540721/Marketing/Blog/Quarto_Cheat_Sheet.pdf)
```

_________

## Week 1: (Jan 11---15) {-}


* Before the first class meeting, read Chapter 1 (Getting Started with Data in R) of [MD](https://moderndive.com/1-getting-started.html)---pgs 1-20

* Before the first class meeting, read Chapter 1 [Why Git? Why GitHub?](https://happygitwithr.com/big-picture) of Happy Git With `R`.

* Become familiar with the Appstate [RStudio/POSIT workbench](https://mathr.appstate.edu/) server. You will use your Appstate user name and password to log in to the server.  You must be registered in the class to access the server.

We will walk through everything outlined below in class.  If you want to complete the setup before class that is fine.    

* Sign-up for a free account on [GitHub](https://github.com).  When you register for a free individual GitHub account, request a [student discount](https://education.github.com) to obtain a few private repositories as well as unlimited public repositories.  Please use something similar to **FirstNameLastName** as your username when you register with GitHub.  For example, my username on GitHub is *alanarnholt*. If you have a popular name such as John Smith, you may need to provide some other distinguishing characteristic in your username.  

* Introduce yourself to Git by following the directions in [HappyGitWithR](https://happygitwithr.com/hello-git)

* Cache your credentials and set up a personal access token (PAT) by following the directions in [HappyGitWithR](https://happygitwithr.com/credential-caching.html).

* TL;DR the chapters in Happy Git With R --- follow this document to [Set up Git and GitHub](../Handouts/setup.html)

* [VIDEO of the setup process](https://drive.google.com/file/d/1L-v9qAVHWtvXOTYjY8wvedH5VyzmeQeL/view?usp=drive_link)

* Complete [PS-01](https://classroom.github.com/a/faGtQ02z) due by 5:00 pm Jan 14 
* [VIDEO of how to accept and clone the assignment](https://drive.google.com/file/d/1JUag-0U-reD_JcKHvez50I_4R-CCMUMt/view?usp=drive_link)
 
```{block, week1optional, type='rmdoptional'}
#### Optional {-}

* For additional ideas with Quarto documents watch [Hello,  Quarto: A World of Possibilities (for Reproducible Publishing)](https://www.youtube.com/watch?v=Qrz2rUWM-uY)
*  _Introduction to R_ [slides](https://alanarnholt.github.io/GeneralStatistics/rmarkdown/IntroToR.html)

* Watch Paul the Octopus [clip](https://www.youtube.com/watch?v=3ESGpRUMj9E) (61 seconds).

* You may want to install [Git](http://git-scm.com/downloads), [R](http://cran.r-project.org), [RStudio](http://www.rstudio.com/products/rstudio/download/), [zotero](https://www.zotero.org), and optionally [$LaTeX$](http://www.ctan.org/starter) on your personal computer. If you do, you will want to follow Jenny Bryan's excellent advice for [installing R and RStudio](http://stat545-ubc.github.io/block000_r-rstudio-install.html) and [installing Git](http://stat545-ubc.github.io/git01_git-install.html).  Jenny's advice is also in chapters 6 and 7 of [Happy Git and GitHub for the useR](http://happygitwithr.com/).  Note: [Git](http://git-scm.com/downloads), [R](http://cran.r-project.org), [RStudio](http://www.rstudio.com/products/rstudio/download/), and [$LaTeX$](http://www.ctan.org/starter) are installed on the [Appstate RStudio](https://mathr.appstate.edu/) server.

* Watch the following videos as appropriate:

* [Install R on Mac (2 min)](https://www.youtube.com/watch?v=lJxVRgiX-ik)    

* [Install R for Windows (3 min)](https://www.youtube.com/watch?v=LII6of-5Odw)    

* [Install R and RStudio on Windows (5 min)](https://www.youtube.com/watch?v=eD07NznguA4)  

* Work through chapter 1 (Git and GitHub) of [DSWR](https://stat-ata-asu.github.io/R_DS_BD2020/).  Make sure RStudio is set up to communicate with Git by following the directions in [HappyGitWithR](https://happygitwithr.com/hello-git.html) for introducing yourself to Git.

* Work through chapter 2 (Introduction to R) of [DSWR](https://stat-ata-asu.github.io/R_DS_BD2020/)

* [Reading in Data](https://alanarnholt.github.io/STT3850/Handouts/WorkingWithDataRevised.html)

```

______________

## Week 2: (No Class Monday Jan 18; Class Jan 19---22) {-}


* [Lecture Slides](../Rmarkdown/Week02/Week2_Lect.pdf)

* Complete the **Data Visualization** chapter of _Introduction to the Tidyverse_ --- [DataCamp](https://app.datacamp.com/groups/stt3850-s2026/assignments) --- Due NLT 5:00 pm Jan 18

* Before class read chapter 2 (Data Visualization) of [MD](https://moderndive.com/2-viz.html) --- pgs 21-62

* Complete the **Types of Visualizations** chapter of _Introduction to the Tidyverse_ --- [DataCamp](https://app.datacamp.com/groups/stt3850-s2026/assignments) --- Due NLT 5:00 pm Jan 19

* Complete [PS-02](https://classroom.github.com/a/mXggb_gR) due by 5:00 pm Jan 21

* **Quiz #1** Jan 22

```{block, week2optional, type='rmdoptional'}
#### Optional {-}

* Read [Getting used to R, RStudio, and R Markdown](https://ismayc.github.io/rbasics-book/)

* Work through chapter 5 (Using `ggplot2`) of [DSWR](https://stat-ata-asu.github.io/R_DS_BD2020/)

* Complete _Data Visualization with `ggplot2`_ (Part 1) [(DataCamp)](https://www.datacamp.com/)

```

__________________


## Week 3: (Jan 25---Jan 29) {-}

* [Lecture Slides](../Rmarkdown/Week03/Week3_Lect.pdf)

* Before class read chapter 3 (Data Wrangling) of [MD](https://moderndive.com/3-wrangling.html) --- pgs 65-96

* Complete the **Data Wrangling** chapter of _Introduction to the Tidyverse_ --- [DataCamp](https://app.datacamp.com/groups/stt3850-s2026/assignments) --- Due NLT 5:00 pm Jan 24

* Complete the **Grouping and Summarizing** chapter of _Introduction to the Tidyverse_ --- [DataCamp](https://app.datacamp.com/groups/stt3850-s2026/assignments) --- Due NLT 5:00 pm Jan 25

* [Scales](../Quarto/scales.html)

* Complete [PS-03](https://classroom.github.com/a/ntSeGMft) by 5:00 pm Jan 28

* In-class work on [dplyr-CH1-handout](https://classroom.github.com/a/V9EAEhmH)

* **Quiz #2** - Jan 29




```{block, test3, type='rmdexercise'}
Test yourself:

1. [R Markdown Practice](RMarkdown.pdf)
2. [R Markdown Extra Credit](RMarkdownEC.pdf)
3. [LaTeX/knitr Extra Credit](knitrEC.pdf)
```

```{block, week3optional, type='rmdoptional'}
#### Optional {-}

* Watch [Selecting Variables Using `dplyr` in R](https://www.youtube.com/watch?v=vDgP7J1qMCI)

* Watch [Filtering Observations Using `dplyr` in R](https://www.youtube.com/watch?v=KWs8VNeWlbE)

* Watch [Arranging Your Data Using `dplyr` in R](https://www.youtube.com/watch?v=BN9-zPuM-2g)

* Watch [Adding New Columns Using `dplyr` in R](https://www.youtube.com/watch?v=stNOP4B1aGE)

* Watch [Creating Summary Statistics Using `dplyr` in R](https://www.youtube.com/watch?v=PAE8oaC0vtk)

* Watch [Practicing your Tidyverse Skills: Advanced Filters with Dplyr](https://www.youtube.com/watch?v=w5veSzXK1jw) - [Quarto Document](https://stat-ata-asu.github.io/DataScience_1/Quarto/AdvancedFilters.html)

* Watch [Practicing Your Tidyverse Skills: `if_else()` Functions with `dplyr`](https://www.youtube.com/watch?v=-j5Hbwua0fE)

* Watch [Practicing your Tidyverse Skills: `case_when()` Functions with `dplyr`](https://www.youtube.com/watch?v=22KMfxZgCqE)

* Posit [Cheat Sheets](https://posit.co/resources/cheatsheets/)

* Work through chapter 3 (Starting with Data) of [DSWR](https://stat-ata-asu.github.io/R_DS_BD2020/)

* Work through chapter 4 (Data Manipulation) of [DSWR](https://stat-ata-asu.github.io/R_DS_BD2020/)

* In-class work on [dplyr-CH2-handout](https://classroom.github.com/a/1f3Hi26V) 

* In-class work on [dplyr-CH3-handout](https://classroom.github.com/a/yKruzgNV) 

* In-class work on [dplyr-CH4-handout](https://classroom.github.com/a/GlLktIRG)  
```

___________

## Week 4: (Feb 1---5) {-}


* [Lecture Slides](../Rmarkdown/Week04/Week4_Lect.pdf)

* Complete the **Introduction to Modeling** chapter of _Modeling with Data in the Tidyverse_ --- [DataCamp](https://app.datacamp.com/groups/stt3850-s2026/assignments) --- Due NLT 5:00 pm Jan 31

* Before class read chapter 5 (Basic Regression) of [MD](https://moderndive.com/5-regression.html) --- pgs 119-160

* In class go over this [document](../Handouts/regression.html)

* Complete the **Modeling with Basic Regression** chapter of _Modeling with Data in the Tidyverse_ --- [DataCamp](https://app.datacamp.com/groups/stt3850-s2026/assignments) --- Due NLT 5:00 pm Feb 1

* Complete [PS-04](https://classroom.github.com/a/vBV1KD6v) due by 5:00 pm Feb 4

* **Quiz #3** Feb 5 


```{block, week4optional, type='rmdoptional'}
#### Optional {-}

* Read chapter 4 (Data Importing and "Tidy" Data) of [MD](https://moderndive.com/4-tidy.html) --- pgs 99-117

* Read the [Git and GitHub](http://r-pkgs.had.co.nz/git.html) chapter from Hadley Wickham's book [R Packages](http://r-pkgs.had.co.nz/)

* Brian Caffo's take on [R IDEs](https://www.youtube.com/watch?v=O2UFfiGdGFA)

```

__________________



## Week 5: (Feb 8---12) {-}

* [Lecture Slides](../Rmarkdown/Week05/Week5_Lect.pdf)

* Complete the **Modeling with Multiple Regression** chapter of _Modeling with Data in the Tidyverse_ --- [DataCamp](https://app.datacamp.com/groups/stt3850-s2026/assignments)---Due NLT 5:00 pm Feb 7

* Before class read chapter 6 (Multiple Regression) of [MD](https://moderndive.com/6-multiple-regression.html) --- pgs 161-191

* Regression with a single [categorical variable](../Handouts/RegWithCategoricalVariables.html) handout.


* Complete the **Model Assessment and Selection** chapter of _Modeling with Data in the Tidyverse_ --- [DataCamp](https://app.datacamp.com/groups/stt3850-s2026/assignments) --- Due NLT 5:00 pm Feb 8

* Complete [PS-05](https://classroom.github.com/a/o_eNFe3g) by 5:00 pm Feb 11

* **Quiz #4** Feb 12


```{block, week5optional, type='rmdoptional'}
#### Optional {-}

* Complete _Correlation and Regression in R_ [(DataCamp)](https://www.datacamp.com/)

* For additional ideas with Quarto documents watch [Hello,  Quarto: A World of Possibilities (for Reproducible Publishing)](https://www.youtube.com/watch?v=Qrz2rUWM-uY)
```

_______________

## Week 6: (Feb 15---19) {-}

* [Lecture Slides](../Rmarkdown/Week06/Week6_Lect.pdf)

* Complete the **Summary Statistics** chapter of _Introduction to Statistics in R_ --- [DataCamp](https://app.datacamp.com/groups/stt3850-s2026/assignments) --- Due NLT 5:00 pm Feb 14

* Before class read/review chapter 6 (Multiple Regression) of [MD](https://moderndive.com/6-multiple-regression.html) --- pgs 161-191

* Class [notes](../Handouts/RegHandout.html) for one quantitative and one qualitative predictor

* Go over in class [_Misc Regression_](../Rmarkdown/MiscRegression.html)

* Complete the **Random Numbers and Probability** chapter of _Introduction to Statistics in R_ --- [DataCamp](https://app.datacamp.com/groups/stt3850-s2026/assignments) --- Due NLT 5:00 pm Feb 15

* Complete [PS-06](https://classroom.github.com/a/IkY2uHOT) by 5:00 pm Feb 18 

* **Quiz #5**  Feb 19

```{block, week6optional, type='rmdoptional'}
#### Optional {-}

* Answer the questions at the end of [_Misc Regression_](../Rmarkdown/MiscRegression.html) for extra credit 

* Work on [Is this Discrimination?](../Rmarkdown/ClassAssignment.html)

* Some ideas for how to answer the [Is this Discrimination?](../Rmarkdown/discrimination.html)
```

_____________


## Week 7: (Feb 22---26) {-}


* [Lecture Slides](../Rmarkdown/Week07/Week7_Lect.pdf)

* Complete the **The binomial distribution** chapter in _Foundations of Probability in R_ --- [DataCamp](https://app.datacamp.com/groups/stt3850-s2026/assignments) --- Due NLT 5:00 pm Feb 21

* Complete the **Laws of probability** chapter in _Foundations of Probability in R_ --- [DataCamp](https://app.datacamp.com/groups/stt3850-s2026/assignments) --- Due NLT 5:00 pm Feb 22

* [Probability](https://alanarnholt.github.io/GeneralStatistics/rmarkdown/probability.html)

* **Quiz #6** Feb 26


```{block, week7optional, type='rmdoptional'}
#### Optional {-}

* [In Class Problems](../Slides/ProbabilityProblems.html)

* [Foundations of Probability with some Extras](https://mathr.appstate.edu/connect/content/4c81be04-9184-4aa6-84bd-a9a1858365f9)

* Complete the **Improving the Report** chapter of _Reporting with R Markdown_--- [DataCamp](https://app.datacamp.com/groups/stt3850-s2026/assignments)

* Complete the **Customizing the Report** chapter of _Reporting with R Markdown_ --- [DataCamp](https://app.datacamp.com/groups/stt3850-s2026/assignments)
```



___________


## Week 8: (Mar 1---5) {-}

* [Lecture Slides](../Rmarkdown/Week07/Week7_Lect.pdf)

* Complete the **Bayesian statistics** chapter in _Foundations of Probability in R_ --- [DataCamp](https://app.datacamp.com/groups/stt3850-s2026/assignments) --- Due NLT 5:00 pm Feb 28

* Complete  the **Related distributions** chapter in _Foundations of Probability in R_ --- [DataCamp](https://app.datacamp.com/groups/stt3850-s2026/assignments) --- Due NLT 5:00 pm Mar 1

* **Quiz #7** Mar 5 

_______________

## Spring Break: Mar 8---12

_______________

## Week 9: (Mar 15---19) {-}

* Complete  the **More Distributions and the Central Limit Theorem** chapter in _Introduction to Statistics in R_ --- [DataCamp](https://app.datacamp.com/groups/stt3850-s2026/assignments) --- Due NLT 5:00 pm Mar 14

* Before class read chapter 7 (Sampling) of [MD](https://moderndive.com/7-sampling.html) --- pgs 195-232

* Complete (will go over most questions in class) [Sampling Distributions Lab](https://classroom.github.com/a/CRAoB8Zm) by 5:00 pm Mar 15 --- not graded
[Partial Solution](https://mathr.appstate.edu/connect/content/2d388531-2e05-485b-9f58-83855a1437e3)

* Start [PS-07](https://classroom.github.com/a/yauAfDyL) due by 5:00 pm Mar 18

* **Quiz #8**  Mar 19



```{block, week9optional, type='rmdoptional'}
#### Optional {-}

* [Sampling Distributions](../Handouts/EVuniform.html)

* Read Chapter 4 of MSWR --- Sampling Distributions; [Problems 2, 5, 12-16](../Homework/Chapter4HWK.Rmd)

```

___________________________


## Week 10: (Mar 22---26) {-}

* [Lecture Slides](../Rmarkdown/Week10/Week10_Lect.pdf)

* [Chapter 5 notes](../Notes/Children/BootStrap2.html)

* Read Chapter 5 of MSWR

* Complete the **Bootstrapping for Estimating a Parameter** chapter in _Inference for Numerical Data in R_ --- [DataCamp](https://app.datacamp.com/groups/stt3850-s2026/assignments) --- Due NLT 5:00 pm Mar 21

* Before class read chapter 8 (Bootstrapping and Confidence Intervals) of [MD](https://moderndive.com/8-confidence-intervals.html) --- pgs 233-305

* Complete the **Introducing the t-distribution** chapter in _Inference for Numerical Data in R_ --- [DataCamp](https://app.datacamp.com/groups/stt3850-s2026/assignments) --- Due NLT 5:00 pm Mar 22

* Complete the **Inference for Difference in Two Parameters** chapter in _Inference for Numerical Data in R_ --- [DataCamp](https://app.datacamp.com/groups/stt3850-s2026/assignments) --- Due NLT 5:00 pm Mar 23

* Bootstrap [Example](https://stat-ata-asu.github.io/STT3851ClassRepo/Rmarkdown/TheBootstrap.html)

* **Quiz #9** Mar 26


```{block, week10optional, type='rmdoptional'}
#### Optional {-}

* [Misc `infer` Examples](../Rmarkdown/ExamplesInfer.html)

* [Inference Examples used in class](../Handouts/InferenceExamples.pdf)

* [Bootstrap Percentile CI examples](../Rmarkdown/BSPCI_examples.html)
```

_______________________


## Week 11: (Mar 29---Apr 2) {-}

* [Lecture Slides for weeks 11, 12, and 13](../Rmarkdown/Week11_12_13/Week11_12_13.pdf)

* Before class review chapter 8 (Bootstrapping and Confidence Intervals) of [MD](https://moderndive.com/8-confidence-intervals.html) --- pgs 233-305

* Read Chapter 7 of MSWR

* [Chapter 7 notes](../Notes/Children/ConfidenceIntervals2.html)

* [Bootstrap $t$](../Rmarkdown/MoreBootstrapping.html)

* Complete [PS-08](https://classroom.github.com/a/usPPma58) by 5:00 pm Apr 1

* **Quiz #10** Apr 2

_____________________




```{block, week11optional, type='rmdoptional'}
#### Optional {-}

* [Misc `infer` Examples](../Rmarkdown/ExamplesInfer.html)

* [Inference Examples used in class](../Handouts/InferenceExamples.pdf)

* [Bootstrap Percentile CI examples](../Rmarkdown/BSPCI_examples.html)

* [Inference for Numerical Data in R](https://mathr.appstate.edu/connect/content/23ecb8d9-19ee-4119-bdb6-b692132852da)
```

__________________

## Week 12: (Apr 5---9) {-}

* [Lecture Slides for weeks 11, 12, and 13](../Rmarkdown/Week11_12_13/Week11_12_13.pdf)

* Complete the **Introduction to ideas of inference** chapter of _Foundations of Inference_ --- [DataCamp](https://app.datacamp.com/groups/stt3850-s2026/assignments) --- Due NLT 5:00 pm Apr 4

* Before class read Chapter 9 (Hypothesis Testing) of [MD](https://moderndive.com/9-hypothesis-testing.html) --- pgs 307-360

* Read about [Permutation Testing](../Rmarkdown/PermutationTesting.html) 

* Complete the **Completing a randomization test: gender discrimination** chapter of _Foundations of Inference_ --- [DataCamp](https://app.datacamp.com/groups/stt3850-s2026/assignments) --- Due NLT 5:00 pm Apr 5

* Complete the **Hypothesis testing errors: opportunity cost** chapter of _Foundations of Inference_ --- [DataCamp](https://app.datacamp.com/groups/stt3850-s2026/assignments) --- Due NLT 5:00 pm Apr 6

* **Quiz #11** - Apr 9


```{block, week12optional, type='rmdoptional'}
#### Optional {-}

* [Misc `infer` Examples](../Rmarkdown/ExamplesInfer.html)

* [Inference Examples used in class](../Handouts/InferenceExamples.pdf)
```

______________________



## Week 13: (Apr 12---16) {-}

* [Lecture Slides for weeks 11, 12, and 13](../Rmarkdown/Week11_12_13/Week11_12_13.pdf)

* Complete the **Inference for a Single Parameter** chapter in _Inference for Categorical Data in R_ --- [DataCamp](https://app.datacamp.com/groups/stt3850-s2026/assignments) --- Due NLT 5:00 pm Apr 11

* Before class review Chapter 9 (Hypothesis Testing) of [MD](https://moderndive.com/9-hypothesis-testing.html) --- pgs 307-360

* [Permutation Examples](../Rmarkdown/PermutationExamples.html)

* Complete the **Proportions: Testing and Power** chapter in _Inference for Categorical Data in R_ --- [DataCamp](https://app.datacamp.com/groups/stt3850-s2026/assignments) --- Due NLT 5:00 pm Apr 12

* [One Proportion](../Quarto/onep.html)

* Complete [PS-09](https://classroom.github.com/a/niy6TafV) by 5:00 pm Apr 15

* **Quiz #12** Apr 16

```{block, week13optional, type='rmdoptional'}
#### Optional {-}

* Complete the problems in the [R Markdown file](https://raw.githubusercontent.com/alanarnholt/STT3850/gh-pages/Homework/Chapter5HWK.Rmd) and publish your solution to [RPubs](http://rpubs.com/).

* [Misc R Markdown Examples](../Rmarkdown/MiscRmarkdown.html)
```

_________________

## Week 14: (Apr 19---23) {-}

* [Lecture Slides](../Rmarkdown/Week14_15/ChiSquareTests.pdf)

* [Reading material for weeks 14 and 15](../Rmarkdown/ChiSquareReading.pdf)

* Complete the **Comparing Many Parameters: Independence** chapter in _Inference for Categorical Data in R_ --- [DataCamp](https://app.datacamp.com/groups/stt3850-s2026/assignments) --- Due NLT 5:00 pm Apr 18

* Watch Goodness-Of-Fit video on ASULEARN

* [Goodness-Of-Fit](../Handouts/ChiGOF.html)

* In class [Example 1](../Rmarkdown/InClassNotes.html) and [Example 2](../Quarto/Chi_Square.html)

* **Quiz #13** Apr 23


```{block, week14optional, type='rmdoptional'}
#### Optional {-}
* Complete the problems in the [R Markdown file](https://raw.githubusercontent.com/alanarnholt/STT3850/gh-pages/Homework/Chapter7HWK.Rmd) and publish your solution to [RPubs](http://rpubs.com/) 
```

________________________


## Week 15: (Apr 26---27) {-}

* [Lecture Slides](../Rmarkdown/Week14_15/ChiSquareTests.pdf)

* [Reading material for weeks 14 and 15](../Rmarkdown/ChiSquareReading.pdf)

* Complete the **Comparing Many Parameters: Goodness of Fit** chapter in _Inference for Categorical Data in R_--- [DataCamp](https://app.datacamp.com/groups/stt3850-s2026/assignments) --- Due NLT 5:00 pm Apr 25

* Watch Chi-Square Test of Independence video on ASULEARN

* Watch Chi-Square Test of Homogeneity video on ASULEARN

* [Goodness-Of-Fit](../Handouts/ChiGOF.html)

* In class [Example 1](../Rmarkdown/InClassNotes.html) and [Example 2](../Quarto/Chi_Square.html)

* **Course Review**--- Apr 27


_____________________________________


## Final Exam 

* Section -101 (11:00 am Class): TBD

* Section -102 (1:00 pm Class): TBD

________________

<center> Last Updated on: `r format(Sys.time(), "%b %d, %Y at %X")` </center>

________________